commit before testing
ran into error where pi is not connecting to the arduino

pi@raspberrypi:~/Desktop/project $ node app.js
discovering...
found device. attempting connection...
DBusError: Software caused connection abort
    at _methodReturnHandlers.<computed> (/home/pi/Desktop/project/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/home/pi/Desktop/project/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/home/pi/Desktop/project/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (node:events:526:28)
    at /home/pi/Desktop/project/node_modules/dbus-next/lib/connection.js:132:14
    at Socket.<anonymous> (/home/pi/Desktop/project/node_modules/dbus-next/lib/message.js:65:9)
    at Socket.emit (node:events:526:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'org.bluez.Error.Failed',
  text: 'Software caused connection abort',
  reply: Message {
    type: 3,
    _sent: false,
    _serial: 15255,
    path: undefined,
    interface: undefined,
    member: undefined,
    errorName: 'org.bluez.Error.Failed',
    replySerial: 11,
    destination: ':1.52',
    sender: ':1.12',
    signature: 's',
    body: [ 'Software caused connection abort' ],
    flags: 1
  }
}
^C